#!/bin/bash
./mysecret "int _putchar(char c)" _putchar.c

./mysecret "int _islower(int c)" 0-islower.c

./mysecret "int _isalpha(int c)" 4-isalpha.c

./mysecret "int _abs(int n)" 6-abs.c

./mysecret "int _isupper(int c)" 0-isupper.c

./mysecret "int _isdigit(int c)" 1-isdigit.c

./mysecret "int _strlen(char *s)" 2-strlen.c

./mysecret "void _puts(char *s)" 3-puts.c

./mysecret "char *_strcpy(char *dest, char *src)" 9-strcpy.c

./mysecret "int _atoi(char *s)" 100-atoi.c

./mysecret "char *_strcat(char *dest, char *src)" 0-strcat.c

./mysecret "char *_strncat(char *dest, char *src, int n)" 1-strncat.c

./mysecret "char *_strncpy(char *dest, char *src, int n)" 2-strncpy.c

./mysecret "int _strcmp(char *s1, char *s2)" 3-strcmp.c

./mysecret "char *_memset(char *s, char b, unsigned int n)" 0-memset.c

./mysecret "char *_memcpy(char *dest, char *src, unsigned int n)" 1-memcpy.c

./mysecret "char *_strchr(char *s, char c)" 2-strchr.c

./mysecret "unsigned int _strspn(char *s, char *accept)" 3-strspn.c

./mysecret "char *_strpbrk(char *s, char *accept)" 4-strpbrk.c

./mysecret "char *_strstr(char *haystack, char *needle)" 5-strstr.c
